# -*- coding: utf-8 -*-
"""online_retail_cleaningdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mu2QTm1GGhnW70ia0oOGhliz938L_QZ8
"""

import os
import pandas as pd
import numpy as np

#Data Visualization
import matplotlib.pyplot as plt
import plotly.express as px

df = pd.read_excel('/content/drive/MyDrive/ColabNotebooks/GoalEarn/Prj-8/OnlineRetail.xlsx')

df.head()

df.columns

df.shape

df.info()

df.info(memory_usage='deep')

df.describe()

df.columns.str.lower()

df.columns=['invoice_id', 'item_id', 'description', 'quantity', 'date',
       'unit_price', 'customer_id', 'country']

df.columns

#Number of invoice_id
df.invoice_id.unique().shape

df.invoice_id.unique()

df.date.min() , df.date.max()

df.country.unique().shape

df.customer_id.unique().shape

df.customer_id.isnull().sum()

df.isnull().sum()

df.isnull().sum().sum()

#Create Sales column
df['sales'] = df['quantity'] * df['unit_price']

df.head()

df.sales.quantile([0,0.25,0.5,0.75,1])

df.quantity.quantile([0,0.25,0.5,0.75,1])

df.quantity.max()

df.quantity.min()

cals = list(df.columns)
df = df[cals[0:6]+[cals[-1]]+cals[6:8]]

df.head()

df[df['customer_id'].isnull()]

df['customer_id'].isnull().sum()

#Delete rows that customer_id is NULL
df = df.dropna(subset=['customer_id'])

df['customer_id'].isnull().sum()

"""### Invoice IDs that start with C"""

#Invoice Ids that start with C
df[df['invoice_id'].str.startswith('C' , na=False)]

df[df['invoice_id'].str.startswith('C' , na=False)].shape

#Delete rows that Invoice Id start with C
df = df[~df['invoice_id'].str.startswith('C' , na=False)]

df.shape

"""## Delete unit_price<0 & quantity<0"""

df[df['unit_price']<0].shape

df[df['quantity']<0].shape

df[df['sales'] < 0 ]

df.shape

"""## ** The 99th percentile represents the top 1% of the data, which are usually outliers.**"""

df['unit_price'].max() , df['unit_price'].min()

df['quantity'].max() , df['quantity'].min()

quantity_99 = df['quantity'].quantile(0.99)
quantity_99

unit_price_99=df['unit_price'].quantile(0.99)
unit_price_99

df[(df['unit_price'] <= unit_price_99) ].shape

df[(df['unit_price'] > unit_price_99) ].shape

df = df[df['unit_price'] <= unit_price_99]

df[df['quantity'] <= quantity_99].shape

df[df['quantity'] > quantity_99].shape

df = df[df['quantity'] <= quantity_99 ]

df.shape

df.head()

df.to_csv('/content/drive/MyDrive/ColabNotebooks/GoalEarn/Prj-8/GitHub/online_retail_cleaningdata.csv')

df.to_excel('/content/drive/MyDrive/ColabNotebooks/GoalEarn/Prj-8/GitHub/online_retail_cleaningdata.xlsx')

cus_sum=df.groupby(['customer_id'])['sales'].sum()
cus_sum

df.country.value_counts()

df.customer_id.value_counts()

df.dtypes