# -*- coding: utf-8 -*-
"""rfm_clv_kmeans_normalized_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nONVJwtb6YKpXGNTYFx6vsMpr01ZbnBn
"""

import pandas as pd
import numpy as np
import sklearn.preprocessing as pp


import matplotlib.pyplot as plt
import plotly.express as px

rfm_clv = pd.read_excel('/content/drive/MyDrive/ColabNotebooks/GoalEarn/Prj-8/GitHub/online_retail_rfm_clv(historical)_realdata.xlsx')
rfm_clv

rfm_clv.info()

relevant_cols = ["recency", "frequency", "monetary" , "clv_historical"]
rfm_clv_n = rfm_clv[relevant_cols]

rfm_clv_n.head()



"""
 # **Normalization,Standardization**"""

import sklearn.preprocessing as pp

"""## **MinMax Normalization**"""

scaler1 = pp.MinMaxScaler()
minmax_rfm = scaler1.fit_transform(rfm_clv_n)
minmax_rfm

relevant_cols

# Array → DataFrame

minmax_df = pd.DataFrame(minmax_rfm, columns=relevant_cols)
minmax_df.head()

plt.figure(figsize=(18,8))

# Recency vs Frequency
plt.subplot(2, 3, 1)
plt.scatter(minmax_df['recency'], minmax_df['frequency'], color='green', alpha=0.5)
plt.xlabel('Recency')
plt.ylabel('Frequency')
plt.title('Recency vs Frequency')

# Recency vs Monetary
plt.subplot(2, 3, 2)
plt.scatter(minmax_df['recency'], minmax_df['monetary'], color='blue', alpha=0.5)
plt.xlabel('Recency')
plt.ylabel('Monetary')
plt.title('Recency vs Monetary')

# Frequency vs Monetary
plt.subplot(2, 3, 3)
plt.scatter(minmax_df['frequency'], minmax_df['monetary'], color='red', alpha=0.5)
plt.xlabel('Frequency')
plt.ylabel('Monetary')
plt.title('Frequency vs Monetary')

# recency vs clv_historical
plt.subplot(2, 3, 4)
plt.scatter(minmax_df['recency'], minmax_df['clv_historical'], color='green', alpha=0.6)
plt.xlabel('recency')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - recency vs clv_historical')

# Frequency vs clv_historical
plt.subplot(2, 3, 5)
plt.scatter(minmax_df['frequency'], minmax_df['clv_historical'], color='blue', alpha=0.6)
plt.xlabel('Frequency')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - Frequency vs clv_historical')

# Frequency vs clv_historical
plt.subplot(2, 3, 6)
plt.scatter(minmax_df['monetary'], minmax_df['clv_historical'], color='red', alpha=0.6)
plt.xlabel('Monetary')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - Monetary vs clv_historical')



plt.tight_layout()
plt.show()

"""## **Standard Normalization**"""

scaler2 = pp.StandardScaler()
std_rfm = scaler2.fit_transform(rfm_clv_n)
std_rfm

# Array → DataFrame

std_df = pd.DataFrame(std_rfm , columns=relevant_cols)
std_df.head()

plt.figure(figsize=(18,8))

# Recency vs Frequency
plt.subplot(2, 3, 1)
plt.scatter(std_df['recency'], std_df['frequency'], color='green', alpha=0.5)
plt.xlabel('Recency')
plt.ylabel('Frequency')
plt.title('Recency vs Frequency')

# Recency vs Monetary
plt.subplot(2, 3, 2)
plt.scatter(std_df['recency'], std_df['monetary'], color='blue', alpha=0.5)
plt.xlabel('Recency')
plt.ylabel('Monetary')
plt.title('Recency vs Monetary')

# Frequency vs Monetary
plt.subplot(2, 3, 3)
plt.scatter(std_df['frequency'], std_df['monetary'], color='red', alpha=0.5)
plt.xlabel('Frequency')
plt.ylabel('Monetary')
plt.title('Frequency vs Monetary')

# recency vs clv_historical
plt.subplot(2, 3, 4)
plt.scatter(std_df['recency'], std_df['clv_historical'],color='green', alpha=0.6)
plt.xlabel('recency')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - recency vs clv_historical')

# Frequency vs clv_historical
plt.subplot(2, 3, 5)
plt.scatter(std_df['frequency'], std_df['clv_historical'],color='blue', alpha=0.6)
plt.xlabel('Frequency')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - Frequency vs clv_historical')

# Frequency vs clv_historical
plt.subplot(2, 3, 6)
plt.scatter(std_df['monetary'], std_df['clv_historical'],color='red', alpha=0.6)
plt.xlabel('Monetary')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - Monetary vs clv_historical')



plt.tight_layout()
plt.show()

"""## **Robust Normalization**"""

scaler3 = pp.RobustScaler()
robust_rfm = scaler3.fit_transform(rfm_clv_n)
robust_rfm

# Array → DataFrame

robust_df = pd.DataFrame(robust_rfm , columns = relevant_cols)
robust_df.head()

plt.figure(figsize=(18,8))

# Recency vs Frequency
plt.subplot(2, 3, 1)
plt.scatter(robust_df['recency'], robust_df['frequency'], color='green', alpha=0.5)
plt.xlabel('Recency')
plt.ylabel('Frequency')
plt.title('Recency vs Frequency')

# Recency vs Monetary
plt.subplot(2, 3, 2)
plt.scatter(robust_df['recency'], robust_df['monetary'], color='blue', alpha=0.5)
plt.xlabel('Recency')
plt.ylabel('Monetary')
plt.title('Recency vs Monetary')

# Frequency vs Monetary
plt.subplot(2, 3, 3)
plt.scatter(robust_df['frequency'], robust_df['monetary'], color='red', alpha=0.5)
plt.xlabel('Frequency')
plt.ylabel('Monetary')
plt.title('Frequency vs Monetary')

# recency vs clv_historical
plt.subplot(2, 3, 4)
plt.scatter(robust_df['recency'], robust_df['clv_historical'],color='green', alpha=0.6)
plt.xlabel('recency')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - recency vs clv_historical')

# Frequency vs clv_historical
plt.subplot(2, 3, 5)
plt.scatter(robust_df['frequency'], robust_df['clv_historical'], color='blue', alpha=0.6)
plt.xlabel('Frequency')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - Frequency vs clv_historical')

# Frequency vs clv_historical
plt.subplot(2, 3, 6)
plt.scatter(robust_df['monetary'], robust_df['clv_historical'],color='red', alpha=0.6)
plt.xlabel('Monetary')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - Monetary vs clv_historical')



plt.tight_layout()
plt.show()

"""# **Clustering - KMeans - ElbowPlot**"""

from sklearn.cluster import KMeans

def find_best_clusters(df, maximum_K):

    clusters_centers = []
    k_values = []

    for k in range(1, maximum_K):

        kmeans_model = KMeans(n_clusters = k)
        kmeans_model.fit(df)

        clusters_centers.append(kmeans_model.inertia_)
        k_values.append(k)


    return clusters_centers, k_values

def generate_elbow_plot(clusters_centers, k_values):

    figure = plt.subplots(figsize = (12, 6))
    plt.plot(k_values, clusters_centers, 'o-', color = 'orange')
    plt.xlabel("Number of Clusters (K)")
    plt.ylabel("Cluster Inertia")
    plt.title("Elbow Plot of KMeans")
    plt.show()

clusters_centers, k_values = find_best_clusters(std_rfm, 18)

generate_elbow_plot(clusters_centers, k_values)

kmeans_model = KMeans(n_clusters = 5)
kmeans_model.fit(std_rfm)

std_df["clusters"] = kmeans_model.labels_
std_df.head()

plt.figure(figsize=(18,8))

# Recency vs Frequency
plt.subplot(2, 3, 1)
plt.scatter(std_df['recency'], std_df['frequency'], c = std_df["clusters"], alpha=0.5)
plt.xlabel('Recency')
plt.ylabel('Frequency')
plt.title('Recency vs Frequency')

# Recency vs Monetary
plt.subplot(2, 3, 2)
plt.scatter(std_df['recency'], std_df['monetary'], c = std_df["clusters"], alpha=0.5)
plt.xlabel('Recency')
plt.ylabel('Monetary')
plt.title('Recency vs Monetary')

# Frequency vs Monetary
plt.subplot(2, 3, 3)
plt.scatter(std_df['frequency'], std_df['monetary'], c = std_df["clusters"], alpha=0.5)
plt.xlabel('Frequency')
plt.ylabel('Monetary')
plt.title('Frequency vs Monetary')

# recency vs clv_historical
plt.subplot(2, 3, 4)
plt.scatter(std_df['recency'], std_df['clv_historical'], c = std_df["clusters"] , alpha=0.6)
plt.xlabel('recency')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - recency vs clv_historical')

# Frequency vs clv_historical
plt.subplot(2, 3, 5)
plt.scatter(std_df['frequency'], std_df['clv_historical'], c = std_df["clusters"], alpha=0.6)
plt.xlabel('Frequency')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - Frequency vs clv_historical')

# Frequency vs clv_historical
plt.subplot(2, 3, 6)
plt.scatter(std_df['monetary'], std_df['clv_historical'], c = std_df["clusters"], alpha=0.6)
plt.xlabel('Monetary')
plt.ylabel('clv_historical')
plt.title('Scatter Plot - Monetary vs clv_historical')


plt.tight_layout()
plt.show()

rfm_clv

std_df

std_df['customer_id'] = rfm_clv['customer_id'].values
std_df

std_df.to_csv('/content/drive/MyDrive/ColabNotebooks/GoalEarn/Prj-8/GitHub/rfm_clv_kmeans_normalized_data.csv')

std_df.to_excel('/content/drive/MyDrive/ColabNotebooks/GoalEarn/Prj-8/GitHub/rfm_clv_kmeans_normalized_data.xlsx')

cluster_profile = std_df.groupby("clusters").agg({
                                                'recency' : 'mean',
                                                'frequency' : 'mean',
                                                'monetary' : 'mean',
                                                'clv_historical' : 'mean',
                                                'customer_id' : 'count'
}).rename(columns = {"customer_id" : "customer_count"})

cluster_profile

cluster_profile.to_csv('/content/drive/MyDrive/ColabNotebooks/GoalEarn/Prj-8/GitHub/rfm_clv_kmeans_normalized_data_mean.csv')

cluster_profile.to_excel('/content/drive/MyDrive/ColabNotebooks/GoalEarn/Prj-8/GitHub/rfm_clv_kmeans_normalized_data_mean.xlsx')

cluster_customers = std_df.groupby("clusters")['customer_id'].apply(list)
cluster_customers

cluster_customers.columns = ['clusters', 'customer_id']
cluster_customers

cluster_customers_exploded = std_df[['clusters', 'customer_id']].sort_values(by='clusters')
cluster_customers_exploded

cluster_customers_exploded[cluster_customers_exploded['clusters']==3]